# fmt: ini

[bastion]
13.38.73.217 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/td-j1-key-bastion

[cible]
172.31.50.88 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/td-j1-key-web ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyCommand="ssh -i ~/.ssh/td-j1-key-bastion -W %h:%p -o StrictHostKeyChecking=no ubuntu@13.38.73.217"'
