# fmt: ini

[bastion]
15.237.251.43 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/td-j1-key-bastion

[web]
172.31.60.68 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/td-j1-key-web ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyCommand="ssh -i ~/.ssh/td-j1-key-bastion -o StrictHostKeyChecking=no -W %h:%p ubuntu@35.180.24.89"'
